config/routes.rb
Fourchal::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users do
    resources :competition_entries do
      resources :challenge_entries
    end
  end

  resources :competitions do
    resources :competition_entries
  end

  resources :competition_entries do
    resources :challenges do
      resources :challenge_entries
    end
  end

  resources :challenge_entries
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :competitions_attributes

  has_many :competitions
  has_many :competition_entries
  has_many :challenge_entries, :through => :competition_entries

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @points = @user.challenge_entries.where(:complete => true).sum(:points)
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = collection_select :user, :role_ids, Role.all, :id, :name
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User

.info
  %h4 User: #{@user.name}
  %h4 Email: #{@user.email if @user.email}
  %h4 Total number of points: #{ @points }

.competitions
  %h4 My Competitions
  - @user.competitions.each do |competition|
    = link_to competition.name, competition_path(competition)
    %br

.competition_entries
  %h4 My Competition Entries
  - @user.competition_entries.each do |entry|
    = link_to entry.competition.name,
      edit_competition_competition_entry_path(entry.competition.id, entry)
    %br

.challenge_entries
  %h4 My Challenge Entries
  - @user.challenge_entries.each do |entry|
    = link_to entry.challenge.title,
      edit_competition_competition_entry_path(entry.competition_entry.competition.id, entry)
    %br