config/routes.rb
Fourchal::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users do
    resources :competition_entries do
      resources :challenge_entries
    end
  end

  resources :competitions do
    resources :competition_entries
  end

  resources :competition_entries do
    resources :challenges do
      resources :challenge_entries
    end
  end

  resources :challenge_entries
end

app/models/competition_entry.rb
class CompetitionEntry < ActiveRecord::Base
  belongs_to :competition
  belongs_to :user
  # attr_accessible :title, :body
  
  attr_accessible :user_id, :competition_id
  has_many :challenge_entries

  validates :user_id, :uniqueness => { :scope => :competition_id }
end

app/controllers/competition_entries_controller.rb
class CompetitionEntriesController < ApplicationController
  def index
    @competitions = CompetitionEntry.where(:competition_id => params[:competition_id])
  end

  def show
    @competition = Competition.find(params[:competition_id])
    @competition_entry = CompetitionEntry.where(:user_id => current_user,
                                                :competition_id => @competition)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition_entry }
    end
  end

  def new
    @competition = Competition.find(params[:competition_id])
    @competition_entry = CompetitionEntry.where(:user_id => current_user,
                                                :competition_id => @competition)
    if @competition_entry.count == 0
      @competition_entry = @competition.competition_entries.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @competition_entry }
      end
    elsif @competition_entry.count == 1
      redirect_to edit_competition_competition_entry_path(@competition, @competition_entry.first)
    end
  end

  def create
    #@competition = Competition.find(params[:competition_id])
    @competition_entry = CompetitionEntry.create(:user_id => current_user,
                                                 :competition_id => params[:competition_id])

    respond_to do |format|
      if @competition_entry.save
        format.html { redirect_to edit_competition_competition_entry_path(@competition_entry.competition, @competition_entry), notice: 'Competition Entry was successfully created.' }
        format.json { render json: @competition_entry, status: :created, location: @competition_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @competition_entry.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
    @competition_entry = CompetitionEntry.find(params[:id])
    @competition = @competition_entry.competition
  end

  def update
    @competition_entry = CompetitionEntry.find(params[:id])

    respond_to do |format|
      if @competition_entry.update_attributes(params[:competition_entry])
        format.html { redirect_to edit_competition_competition_entry_path(@competition_entry.competition, @competition_entry), notice: 'Competition Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end
end

app/helpers/competition_entries_helper.rb
module CompetitionEntriesHelper
end

app/views/competition_entries/_form.html.haml
= form_for @competition_entry do |f|
  -@competition.challenges.each do |challenge|
    .challenge
      %p
        Title: #{ challenge.title }
        %br
        Description: #{ challenge.description }
        %br
        Points: #{ challenge.points }
        %br
        Prize: #{ challenge.prize }
        %br
        Badge: #{ challenge.badge }
        %br

      = link_to "Complete Challenge", new_competition_entry_challenge_challenge_entry_path(@competition_entry.id, challenge.id)


  .actions
    = f.submit 'Save'

app/views/competition_entries/edit.html.haml
%h1 Editing Competition Entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', competition_competition_entries_path

app/views/competition_entries/index.html.haml
%h1 Listing competition entries

%table
  %tr
    %th User
    %th
    %th
    %th

  - @competitions.each do |competition|
    %tr
      %td= competition.user.name
      %td= link_to 'Show', competition
      %td= link_to 'Edit', edit_competition_path(competition)
      %td= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Competition', new_competition_path

app/views/competition_entries/new.html.haml
%h1 New Competition Entry

= render 'form'

app/views/competition_entries/show.html.haml
%p#notice= notice

%p
  %b Name of the Competition:
  = @competition.name
%p
  %b Starttime:
  = @competition.startTime
%p
  %b Endtime:
  = @competition.endTime
%p
  %b User:
  = @competition.user.name


.challenges
  %table
    %tr
      %th Title
      %th Description
      %th Validation
      %th Badge
      %th Prize
      %th Points
    - @competition.challenges.each do |challenge|
      %tr
        %td #{ challenge.title }
        %td #{ challenge.description }
        %td #{ challenge.validation }
        %td #{ challenge.badge }
        %td #{ challenge.prize }
        %td #{ challenge.points }


= link_to 'Edit', edit_competition_path(@competition)
\|
= link_to 'Back', competitions_path