config/routes.rb
Fourchal::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users

  resources :users do
    resources :competition_entries do
      resources :challenge_entries
    end
  end

  resources :competitions do
    resources :competition_entries
  end

  resources :competition_entries do
    resources :challenges do
      resources :challenge_entries
    end
  end

  resources :challenge_entries
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul{:class=> "nav pull-right"}
  %li
    = link_to "Home", root_path, {:class=>'nav-link'}
  - if user_signed_in?
    %li
      = link_to 'Profile', user_path(current_user), :class=>'nav-link'
    %li
      = link_to 'Logout', destroy_user_session_path, :class=>'nav-link', :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path, {:class=>'nav-link'}
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path, {:class=>'nav-link'}
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path, {:class=>'nav-link'}
  - else
    %li
      = link_to 'Sign up', new_user_registration_path, {:class=>'nav-link'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Fourchal"
      %meta{:content => content_for?(:description) ? yield(:description) : "Fourchal", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
      = link_to image_tag('logo.png', :class=>'logo'), root_path
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main